### ISSUE TITLE
why ds.dataloader_init is poisoned

### ISSUE THREAD

**Issue by lidazui-creat** [UCF-ML-Research/SSL-Cleanse#1]
In your code of detector.py, if I am right ,ds.dataloader_init is used to form k clusters,so here ds.dataloader should be clean data?why you  add a trigger on the dataset?

**Comment by UCF-ML-Research** [comment]
Yes, ds.dataloader_init are clean images. We didn't patch trigger on it.

the hyperparameter ratio of it is how many clean samples are used in the detection.

https://github.com/UCF-ML-Research/SSL-Cleanse/blob/05f882f4fb2246d281ee0360d7e8895f1f155a7f/detector/core/detector.py#L55
